metrics:
  - name: test_wave
    type: gauge
    help: "Test periodic wave"
    profile:
      type: periodic
      amplitude: 10
      period: 120
      base: 50
    noise:
      type: uniform
      magnitude: 30
    bounds:
      min: 0
      max: 100
  - name: test_noised_4gi
    type: gauge
    help: "Test periodic wave"
    profile:
      type: constant
      value: 4294967296 # 4 GiB
    noise:
      type: percentage
      magnitude: 30
